import { StrictMode, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import type { ActionCard, ChallengeTemplate, CheckIn, FeedItem, HabitProtocol, SessionState, TemplateCommunity, TemplateParticipant, TransformationReport, Visibility } from "@rawhabit/shared";
import "./styles.css";

const getJson = <T,>(path: string) => fetch(path).then(async (response) => {
  if (!response.ok) throw new Error((await response.json()).error ?? "Request failed");
  return response.json() as Promise<T>;
});

function App() {
  const [templates, setTemplates] = useState<ChallengeTemplate[]>([]);
  const [session, setSession] = useState<SessionState | null>(null);
  const [feed, setFeed] = useState<FeedItem[]>([]);
  const [result, setResult] = useState<CheckIn | null>(null);
  const [report, setReport] = useState<TransformationReport | null>(null);
  const [community, setCommunity] = useState<{ data: TemplateCommunity; participants: TemplateParticipant[] } | null>(null);
  const [editingProtocol, setEditingProtocol] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const template = templates.find((item) => item.id === session?.activeChallenge?.templateId);

  const refresh = async () => {
    const [nextSession, nextTemplates, nextFeed] = await Promise.all([getJson<SessionState>("/api/session"), getJson<ChallengeTemplate[]>("/api/templates"), getJson<FeedItem[]>("/api/feed")]);
    setSession(nextSession); setTemplates(nextTemplates); setFeed(nextFeed); setReport(nextSession.report);
  };
  useEffect(() => { refresh().catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const mutate = async (path: string, options?: RequestInit) => {
    setError("");
    const controller = new AbortController();
    const timeout = window.setTimeout(() => controller.abort(), 25_000);
    let response: Response;
    try {
      response = await fetch(path, { ...options, signal: controller.signal });
    } catch (cause) {
      if ((cause as Error).name === "AbortError") throw new Error("Coaching took too long. Check that the server is running, then try again.");
      throw new Error("We couldn’t reach the coaching server. Check that bun dev is running, then try again.");
    } finally {
      window.clearTimeout(timeout);
    }
    if (!response.ok) throw new Error((await response.json()).error ?? "Something went wrong");
    return response.json();
  };
  const start = async (templateId: string) => { try { setSession(await mutate("/api/challenge/start", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ templateId }) })); setEditingProtocol(false); setResult(null); setReport(null); } catch (cause) { setError((cause as Error).message); } };
  const clone = async (feedItemId: string) => { try { setSession(await mutate(`/api/feed/${feedItemId}/clone`, { method: "POST" })); setEditingProtocol(false); setResult(null); setReport(null); } catch (cause) { setError((cause as Error).message); } };
  const openCommunity = async (templateId: string) => { try { const [data, participants] = await Promise.all([getJson<TemplateCommunity>(`/api/templates/${templateId}/community`), getJson<TemplateParticipant[]>(`/api/templates/${templateId}/participants`)]); setCommunity({ data, participants }); } catch (cause) { setError((cause as Error).message); } };
  const submit = async (audio: Blob | null, video: Blob | null, transcript: string, visibility: Visibility) => {
    try {
      const upload = video ? await mutate("/api/media", { method: "POST", headers: { "Content-Type": video.type || "video/webm" }, body: video }) as { mediaUrl: string } : undefined;
      const query = new URLSearchParams({ visibility, ...(transcript ? { demoTranscript: transcript } : {}), ...(upload ? { mediaUrl: upload.mediaUrl } : {}) });
      const checkIn = await mutate(`/api/check-ins?${query}`, { method: "POST", headers: audio ? { "Content-Type": audio.type || "audio/webm" } : { "Content-Type": "application/json" }, body: audio ?? undefined }) as { checkIn: CheckIn; feedItem?: FeedItem; actionCard: ActionCard };
      setResult(checkIn.checkIn); setSession((current) => current ? { ...current, activeActionCard: checkIn.actionCard } : current); if (checkIn.feedItem) setFeed((items) => [checkIn.feedItem!, ...items]);
    } catch (cause) { setError((cause as Error).message); }
  };
  const complete = async () => { try { setSession(await mutate("/api/challenge/dev-complete", { method: "POST" })); } catch (cause) { setError((cause as Error).message); } };
  const generateReport = async () => { try { const next = await mutate("/api/graduate/report", { method: "POST" }) as TransformationReport; setReport(next); } catch (cause) { setError((cause as Error).message); } };
  const victory = async (caption: string) => { try { const item = await mutate("/api/graduate/post", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ caption }) }) as FeedItem; setFeed((items) => [item, ...items]); } catch (cause) { setError((cause as Error).message); } };
  const completeActionCard = async (id: string) => { try { const card = await mutate(`/api/action-cards/${id}/complete`, { method: "POST" }) as ActionCard; setSession((current) => current ? { ...current, activeActionCard: card } : current); } catch (cause) { setError((cause as Error).message); } };
  const sendFeedback = async (action: string, outcome: "accepted" | "dismissed" | "unhelpful" | "alternative_requested") => { try { await mutate(`/api/check-ins/${result?.id}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, outcome }) }); } catch (cause) { setError((cause as Error).message); } };
  const saveProtocol = async (values: Omit<HabitProtocol, "templateId" | "primaryPrinciple" | "updatedAt">) => { try { const protocol = await mutate("/api/challenge/protocol", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }) as HabitProtocol; setSession((current) => current ? { ...current, habitProtocol: protocol } : current); setEditingProtocol(false); } catch (cause) { setError((cause as Error).message); } };

  if (loading) return <main className="shell loading-state"><p className="eyebrow">RawHabit</p><h1>Finding your people…</h1><div className="skeleton-card" /><div className="skeleton-card short" /></main>;
  return <><a className="skip-link" href="#main-content">Skip to feed</a><header className="topbar"><div className="topbar-inner"><a className="wordmark" href="/" aria-label="RawHabit home">raw<span>habit</span></a><nav aria-label="Primary navigation"><span className="nav-current">Home</span><span>Challenges</span><span>Graduates</span></nav><div className="profile-chip"><span className="avatar maya">M</span><span>{session?.user.status === "graduate" ? "Graduate" : "Maya’s space"}</span></div></div></header><main className="shell" id="main-content">
    {error && <p className="alert">{error}</p>}
    <div className="home-grid"><section className="feed-column"><div className="feed-intro"><p className="eyebrow">The honest feed</p><h1>Progress is better when it’s <em>seen.</em></h1><p>Small reports from people doing the work, in public and without the highlight reel.</p></div><Feed feed={feed} onClone={clone} /></section><aside className="habit-rail" aria-label="Your habit space">
      {!session?.activeChallenge && <TemplatePicker templates={templates} onStart={start} onCommunity={openCommunity} />}
      {session?.activeChallenge && template && session.user.status === "challenger" && <>{!session.habitProtocol || editingProtocol ? <HabitProtocolSetup template={template} protocol={session.habitProtocol} onSave={saveProtocol} /> : <ChallengeDashboard template={template} session={session} onComplete={complete} onCommunity={openCommunity} onEditProtocol={() => setEditingProtocol(true)} />}<Recorder onSubmit={submit} /><CoachResult result={result} onFeedback={sendFeedback} />{session.activeActionCard && <ActionCardView card={session.activeActionCard} onComplete={completeActionCard} />}</>}
      {session?.user.status === "graduate" && template && <Graduate template={template} report={report} onReport={generateReport} onPost={victory} />}
      <p className="rail-note">RawHabit is for support, not diagnosis. If you’re in immediate danger, contact local emergency support.</p>
    </aside></div>
    {community && <CommunitySheet community={community.data} participants={community.participants} onClose={() => setCommunity(null)} />}</main></>;
}

function TemplatePicker({ templates, onStart, onCommunity }: { templates: ChallengeTemplate[]; onStart: (id: string) => void; onCommunity: (id: string) => void }) { return <section className="join-panel"><div className="panel-kicker"><span className="tiny-dot" /> Start something real</div><h2>Your next honest day starts here.</h2><p className="muted">Choose a shared challenge. Make it yours in one tap.</p><div className="challenge-list">{templates.map((template, index) => <article className="challenge-option" key={template.id}><div className={`challenge-mark mark-${index}`}>{template.totalDays}</div><div><p className="official">RawHabit Official</p><h3>{template.title}</h3><p>{template.strategyRules[0]}</p><button className="community-link" onClick={() => onCommunity(template.id)}>See people building this</button></div><button className="text-button" onClick={() => onStart(template.id)}>Join <span aria-hidden="true">→</span></button></article>)}</div></section>; }
function ChallengeDashboard({ template, session, onComplete, onCommunity, onEditProtocol }: { template: ChallengeTemplate; session: SessionState; onComplete: () => void; onCommunity: (id: string) => void; onEditProtocol: () => void }) { const day = session.activeChallenge!.currentDay; const percentage = Math.round((day / template.totalDays) * 100); const initiator = session.activeChallenge?.initiatedBy; const protocol = session.habitProtocol!; return <section className="active-habit"><p className="eyebrow">RawHabit Official · Your active habit</p><h2>{template.title}</h2><div className="progress-label"><span>Day {day} of {template.totalDays}</span><span>{percentage}%</span></div><div className="progress" aria-label={`${percentage}% complete`}><i style={{ width: `${percentage}%` }} /></div>{initiator && <p className="lineage">Initiated by {initiator.displayName}</p>}<div className="protocol-summary"><strong>Your Habit Protocol</strong><span>When: {protocol.trigger}</span><span>Set up: {protocol.environmentChange}</span><span>Smallest step: {protocol.minimumAction}</span><button className="community-link dark" onClick={onEditProtocol}>Edit protocol</button></div><button className="community-link dark" onClick={() => onCommunity(template.id)}>◌ People building this habit</button><p className="rules">Today’s backup: {template.strategyRules[0]}</p><div className="demo"><span>Demo tools</span><button className="secondary" onClick={onComplete}>Complete challenge</button></div></section>; }
function HabitProtocolSetup({ template, protocol, onSave }: { template: ChallengeTemplate; protocol: HabitProtocol | null; onSave: (values: Omit<HabitProtocol, "templateId" | "primaryPrinciple" | "updatedAt">) => Promise<void> }) { const [answers, setAnswers] = useState<Record<string, string>>(() => ({ trigger: protocol?.trigger ?? template.protocolSetup.questions.find((question) => question.id === "trigger")?.options[0] ?? "", environmentChange: protocol?.environmentChange ?? template.protocolSetup.questions.find((question) => question.id === "environmentChange")?.options[0] ?? "", minimumAction: protocol?.minimumAction ?? template.protocolSetup.questions.find((question) => question.id === "minimumAction")?.options[0] ?? "" })); const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); await onSave({ trigger: answers.trigger, environmentChange: answers.environmentChange, minimumAction: answers.minimumAction }); setSaving(false); }; return <section className="card protocol-setup"><p className="eyebrow">Make this work in your real life</p><h2>{protocol ? "Edit your Habit Protocol" : "Set your Habit Protocol"}</h2><p>{template.direction === "build" ? "Make the good habit easy to see and do." : "Make the unwanted habit less visible and harder to do."}</p>{template.protocolSetup.questions.map((question) => <label key={question.id}>{question.label}<select value={answers[question.id]} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))}>{question.options.map((option) => <option key={option}>{option}</option>)}</select></label>)}<button onClick={save} disabled={saving}>{saving ? "Saving…" : "Save my protocol"}</button></section>; }
function Recorder({ onSubmit }: { onSubmit: (audio: Blob | null, video: Blob | null, transcript: string, visibility: Visibility) => Promise<void> }) {
  const [stream, setStream] = useState<MediaStream | null>(null); const [recorders, setRecorders] = useState<MediaRecorder[]>([]); const [videoBlob, setVideoBlob] = useState<Blob | null>(null); const [audioBlob, setAudioBlob] = useState<Blob | null>(null); const [previewUrl, setPreviewUrl] = useState(""); const [seconds, setSeconds] = useState(0); const [visibility, setVisibility] = useState<Visibility>("private"); const [demoTranscript, setDemoTranscript] = useState(""); const [busy, setBusy] = useState(false); const timer = useRef<number | null>(null); const liveVideo = useRef<HTMLVideoElement>(null);
  useEffect(() => { if (liveVideo.current) liveVideo.current.srcObject = stream; }, [stream]);
  useEffect(() => { if (!videoBlob) return; const url = URL.createObjectURL(videoBlob); setPreviewUrl(url); return () => URL.revokeObjectURL(url); }, [videoBlob]);
  const stop = () => recorders.forEach((recorder) => { if (recorder.state === "recording") recorder.stop(); });
  const mime = (types: string[]) => types.find((type) => MediaRecorder.isTypeSupported(type));
  const record = async () => {
    const nextStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
    const videoChunks: BlobPart[] = []; const audioChunks: BlobPart[] = []; let stopped = 0;
    const finish = () => { stopped += 1; if (stopped !== 2) return; nextStream.getTracks().forEach((track) => track.stop()); setStream(null); setRecorders([]); if (timer.current) window.clearInterval(timer.current); };
    const videoType = mime(["video/webm;codecs=vp8,opus", "video/webm"]); const audioType = mime(["audio/webm;codecs=opus", "audio/webm", "audio/mp4"]);
    const videoRecorder = new MediaRecorder(nextStream, videoType ? { mimeType: videoType } : undefined);
    const audioRecorder = new MediaRecorder(new MediaStream(nextStream.getAudioTracks()), audioType ? { mimeType: audioType } : undefined);
    videoRecorder.ondataavailable = (event) => videoChunks.push(event.data); audioRecorder.ondataavailable = (event) => audioChunks.push(event.data);
    videoRecorder.onstop = () => { setVideoBlob(new Blob(videoChunks, { type: videoRecorder.mimeType })); finish(); };
    audioRecorder.onstop = () => { setAudioBlob(new Blob(audioChunks, { type: audioRecorder.mimeType })); finish(); };
    setVideoBlob(null); setAudioBlob(null); setPreviewUrl(""); setStream(nextStream); setRecorders([videoRecorder, audioRecorder]); setSeconds(0); videoRecorder.start(); audioRecorder.start();
    timer.current = window.setInterval(() => setSeconds((value) => { if (value >= 29) { videoRecorder.stop(); audioRecorder.stop(); return 30; } return value + 1; }), 1000);
  };
  const send = async () => { setBusy(true); await onSubmit(audioBlob, videoBlob, demoTranscript, visibility); setBusy(false); };
  return <section className="card recorder"><p className="eyebrow">Daily raw log</p><h2>Record the real moment.</h2>{stream && <div className="camera-frame live"><video ref={liveVideo} autoPlay muted playsInline /><span>● Live camera</span></div>}{previewUrl && !stream && <div className="camera-frame"><video src={previewUrl} controls playsInline /><span>Video will be saved · audio-only sent to coach</span></div>}{!stream && !videoBlob && <button onClick={() => record().catch(() => setDemoTranscript("I had a difficult moment today, but I chose to pause and check in."))}>Record today’s raw log</button>}{stream && <><p className="recording">● Recording {seconds}s / 30s</p><button className="secondary" onClick={stop} disabled={seconds < 15}>Stop recording</button>{seconds < 15 && <small>Keep going for {15 - seconds} seconds.</small>}</>}{audioBlob && <p className="success">Video and audio are ready. Your video will be saved; only audio goes to transcription.</p>}<label>Demo transcript / recording note<textarea value={demoTranscript} onChange={(event) => setDemoTranscript(event.target.value)} placeholder="Optional: use only when you need the demo fallback." /></label><div className="row"><label><input type="radio" checked={visibility === "private"} onChange={() => setVisibility("private")} /> Private</label><label><input type="radio" checked={visibility === "public"} onChange={() => setVisibility("public")} /> Share to feed</label></div><button onClick={send} disabled={busy || (!audioBlob && !demoTranscript)}>{busy ? "Saving & coaching…" : "Save check-in & get coaching"}</button></section>;
}
function CoachResult({ result, onFeedback }: { result: CheckIn | null; onFeedback: (action: string, outcome: "accepted" | "dismissed" | "unhelpful" | "alternative_requested") => void }) { if (!result) return null; const safety = result.coach.riskLevel === "high" || result.coach.riskLevel === "critical"; const live = result.aiRun.transcription === "live" && result.aiRun.coaching === "live"; const action = result.coach.suggestedAction ?? "the suggested action"; return <section className="card result"><p className="eyebrow">Your coach response · {result.coach.riskLevel} support signal</p><p className={`ai-status ${live ? "live" : "fallback"}`}>{live ? "● Live OpenAI · Whisper + GPT-5.6" : `○ Demo fallback · transcription: ${result.aiRun.transcription}, coach: ${result.aiRun.coaching}`}</p><h2>{result.caption}</h2><p>{result.coach.coachMessage}</p><p className="action">Try this: {action}</p><div className="feedback-row"><button onClick={() => onFeedback(action, "accepted")}>Do it</button><button onClick={() => onFeedback(action, "alternative_requested")}>Another option</button><button onClick={() => onFeedback(action, "dismissed")}>Not now</button></div>{safety && <p className="alert">If you may be in immediate danger, reach out to a trusted person or local emergency/crisis support.</p>}</section>; }
function ActionCardView({ card, onComplete }: { card: ActionCard; onComplete: (id: string) => void }) { const done = card.status === "completed"; return <section className="card action-card"><p className="eyebrow">24-hour action card</p><h2>{card.title}</h2><p>{card.instruction}</p><button onClick={() => onComplete(card.id)} disabled={done}>{done ? "Completed" : "Mark complete"}</button></section>; }
function Graduate({ template, report, onReport, onPost }: { template: ChallengeTemplate; report: TransformationReport | null; onReport: () => void; onPost: (caption: string) => void }) { const [caption, setCaption] = useState(""); return <section className="card graduate-view"><p className="eyebrow">Graduate unlocked</p><h2>You completed {template.title}.</h2>{!report ? <button onClick={onReport}>Generate my transformation report</button> : <><div className="report"><h3>What changed</h3>{report.themes.map((item) => <p key={item}>{item}</p>)}<h3>Strengths you practiced</h3>{report.strengths.map((item) => <p key={item}>{item}</p>)}<p className="action">Carry forward: {report.carryForward}</p></div><label>Victory post<textarea value={caption} maxLength={500} onChange={(event) => setCaption(event.target.value)} placeholder="What do you want to remember about this win?" /></label><button onClick={() => { onPost(caption); setCaption(""); }} disabled={!caption.trim()}>Publish victory post</button></>}</section>; }
function CommunitySheet({ community, participants, onClose }: { community: TemplateCommunity; participants: TemplateParticipant[]; onClose: () => void }) { return <div className="sheet-backdrop" role="presentation" onMouseDown={onClose}><section className="community-sheet" role="dialog" aria-modal="true" aria-label="People building this habit" onMouseDown={(event) => event.stopPropagation()}><button className="sheet-close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">RawHabit Official</p><h2>People building this habit</h2><p>{community.participantCount} people have chosen this challenge.</p><div className="participant-grid">{participants.map((person) => <article key={person.userId} className="participant"><span className="avatar">{person.displayName.slice(0, 1)}</span><strong>{person.displayName}</strong><small>Joined the circle</small></article>)}</div></section></div>; }
function Feed({ feed, onClone }: { feed: FeedItem[]; onClone: (id: string) => void }) { return <section className="feed" aria-label="Challenge feed"><div className="feed-heading"><h2>Today in the circle</h2><span>{feed.length} check-ins</span></div>{feed.map((item, index) => { const progress = item.currentDay && item.totalDays ? Math.round((item.currentDay / item.totalDays) * 100) : 100; const initial = item.authorName.slice(0, 1); return <article className={`feed-item post-${index % 3}`} key={item.id}><div className="post-author"><span className={`avatar avatar-${index % 4}`}>{initial}</span><div><strong>{item.authorName}</strong><p>{item.kind === "graduate_post" ? "Graduated today" : item.challengeTitle}</p></div><time dateTime={item.createdAt}>{index === 0 ? "just now" : `${index + 1}h ago`}</time></div>{item.mediaUrl ? <video className="post-media" src={item.mediaUrl} controls playsInline preload="metadata" /> : <div className="post-visual"><span className="visual-day">{item.kind === "graduate_post" ? "Made it" : `Day ${item.currentDay}`}</span><span className="visual-word">raw<br />work</span></div>}<p className="post-caption">{item.caption}</p>{item.currentDay && <div className="post-progress"><div className="progress-label"><span>Day {item.currentDay} of {item.totalDays}</span><span>{progress}%</span></div><div className="progress"><i style={{ width: `${progress}%` }} /></div></div>}{item.coachSnippet && <p className="coach-snippet">Coach note: {item.coachSnippet}</p>}<div className="post-actions"><span>◌ Honest check-in</span>{item.templateId && <button className="text-button" onClick={() => onClone(item.id)}>Join this habit <span aria-hidden="true">→</span></button>}</div></article>; })}</section>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
